export const ProductCategory = [
  {
    id: "1",
    name: "Men's Fashion",
    isActive: true,
    parentCategoryId: "0",
    homePageEnable: true,
    childCategory: [
      {
        id: "4",
        name: "T-Shirts",
        isActive: true,
        parentCategoryId: "1",
        homePageEnable: true,
        childCategory: null,
      },
      {
        id: "5",
        name: "Polo Shirts",
        isActive: true,
        parentCategoryId: "1",
        homePageEnable: true,
        childCategory: null,
      },
      {
        id: "6",
        name: "Formal Shirts",
        isActive: true,
        parentCategoryId: "1",
        homePageEnable: true,
        childCategory: null,
      },
      {
        id: "7",
        name: "Casual Shirts",
        isActive: true,
        parentCategoryId: "1",
        homePageEnable: true,
        childCategory: null,
      },
      {
        id: "8",
        name: "Jeans",
        isActive: true,
        parentCategoryId: "1",
        homePageEnable: true,
        childCategory: null,
      },
    ],
  },
  {
    id: "2",
    name: "Women's Fashion",
    isActive: true,
    parentCategoryId: "0",
    homePageEnable: true,
    childCategory: [
      {
        id: "9",
        name: "Dresses",
        isActive: true,
        parentCategoryId: "2",
        homePageEnable: true,
        childCategory: null,
      },
      {
        id: "10",
        name: "Tops & Blouses",
        isActive: true,
        parentCategoryId: "2",
        homePageEnable: true,
        childCategory: null,
      },
      {
        id: "11",
        name: "Sarees",
        isActive: true,
        parentCategoryId: "2",
        homePageEnable: true,
        childCategory: null,
      },
      {
        id: "12",
        name: "Kurtis",
        isActive: true,
        parentCategoryId: "2",
        homePageEnable: true,
        childCategory: null,
      },
      {
        id: "13",
        name: "Leggings",
        isActive: true,
        parentCategoryId: "2",
        homePageEnable: true,
        childCategory: null,
      },
    ],
  },
  {
    id: "3",
    name: "Kids' Fashion",
    isActive: true,
    parentCategoryId: "0",
    homePageEnable: true,
    childCategory: [
      {
        id: "14",
        name: "T-Shirts",
        isActive: true,
        parentCategoryId: "3",
        homePageEnable: true,
        childCategory: null,
      },
      {
        id: "15",
        name: "Shorts",
        isActive: true,
        parentCategoryId: "3",
        homePageEnable: true,
        childCategory: null,
      },
      {
        id: "16",
        name: "Frocks",
        isActive: true,
        parentCategoryId: "3",
        homePageEnable: true,
        childCategory: null,
      },
      {
        id: "17",
        name: "Jeans",
        isActive: true,
        parentCategoryId: "3",
        homePageEnable: true,
        childCategory: null,
      },
    ],
  },
];
